name: Run Secret Scanning

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan-secrets:
    uses: zeptonow/workflow-hub/.github/workflows/secret-scanning.yml@main
    secrets: inherit
